export interface Sponsor {
  name: string;
  image: string;
  description: string;
  github?: string;
  linkedin?: string;
  twitter?: string;
  instagram?: string;
  isPastSponsor?: boolean;
  isWeSponsor?: boolean;
}

const sponsors: Sponsor[] = [
  {
    name: "DevXavier",
    image: "https://avatars.githubusercontent.com/u/192259212?v=4",
    description: "Student ",
    github: "https://github.com/DevXavierNieto",
  },
    {
    name: "Takashi Arai",
    image: "https://avatars.githubusercontent.com/u/42265874?v=4",
    description: "Student Ryukyu Uni, Japan",
    github: "https://github.com/arataka1313",
    linkedin: "https://www.linkedin.com/in/takashi-arai-2b697b360/",
  },
  {
    name: "Sumit Khanna",
    image: "https://avatars.githubusercontent.com/u/29749122?v=4",
    description: "Developer at slickspender",
    github: "https://github.com/jjackofall",
    twitter: "https://x.com/jjackofall",
  },
  {
    name: "Prakhar Saxena",
    image: "https://avatars.githubusercontent.com/u/111764688?v=4",
    description: "Studying @McMaster University",
    github: "https://www.linkedin.com/in/prakharsaxena5/",
    linkedin: "https://www.linkedin.com/in/prakharsaxena5/",
  },

  {
    name: "Varghese Baby",
    image: "https://avatars.githubusercontent.com/u/68038057?v=4",
    description: "Software Developer",
    github: "https://github.com/varghese25",
    linkedin: "https://www.linkedin.com/in/varghese-baby-138429175/",
    isPastSponsor: true,
  },
 
  {
    name: "Carlos Romero",
    image: "https://avatars.githubusercontent.com/u/119690391?v=4",
    description: "CS Student of La Salle",
    github: "https://github.com/carlosromerorodriguez",
    linkedin: "https://www.linkedin.com/in/carlos-romero-rdgz/",
    isPastSponsor: true,
  },
  {
    name: "Yahya Banouk",
    image: "https://avatars.githubusercontent.com/u/83559441?v=4",
    description: "Full-Stack Engineer at Expersi",
    github: "https://github.com/yahya-banouk",
    linkedin: "https://x.com/Yahya_Banouk",
    twitter: "https://x.com/Yahya_Banouk",
    isPastSponsor: true,
  }, 
  {
    name: "Mike ",
    image: "https://avatars.githubusercontent.com/u/79911993?v=4",
    description: "AI Consultant",
    github: "#",
    linkedin: "#",
    isPastSponsor: true,
  },
  {
    name: "Alex Choi",
    image: "https://avatars.githubusercontent.com/u/64334999?v=4",
    description: "Legacy sponsor",
    github: "https://github.com/alexechoi",
    linkedin: "https://www.linkedin.com/in/alexchoi1/",
    twitter: "https://x.com/alexchhk",
    isPastSponsor: true,
  },
    {
    name: "Renato Maynard",
    image: "https://avatars.githubusercontent.com/u/79546214?v=4",
    description: "M.Sc. in Operations Research",
    github: "https://www.linkedin.com/in/renatomaynardetche/",
    linkedin: "#",
    twitter: "#",
    isPastSponsor: true,
  },
    {
    name: "Tram Khoi Nguyen",
    image: "https://avatars.githubusercontent.com/u/112838098?v=4",
    description: "Student at Tra Vinh, Vietnam",
    github: "https://github.com/khoinguyennni",
    linkedin: "#",
    twitter: "#",
    isPastSponsor: true,
  },
    {
    name: "Bobby Azad",
    image: "https://avatars.githubusercontent.com/u/48394338?v=4",
    description: "BI Developer at Agtegra",
    github: "https://github.com/gbazad93",
    linkedin: "https://www.linkedin.com/in/bobby-azad-b2035b65/",
    twitter: "#",
    isPastSponsor: true,
  },
    {
    name: "Sudarshan Giri",
    image: "https://avatars.githubusercontent.com/u/41857483?v=4",
    description: "Drupal Developer at Webfirst",
    github: "hhttps://github.com/SudarshanGiri",
    linkedin: "https://www.linkedin.com/in/sudarshangiri/",
    twitter: "https://x.com/sudarshanhang",
    isPastSponsor: true,
  },
    {
    name: "Aryan Jaiswal",
    image: "https://pbs.twimg.com/profile_images/1921606118683426816/M1mU3vm8_400x400.jpg",
    description: "Founder @MLSA",
    github: "https://github.com/Aryanjstar",
    linkedin: "https://www.linkedin.com/in/aryanjstar/",
    twitter: "https://x.com/Aryanjstar",
    isPastSponsor: true,
  },
    {
    name: "Kashif Khan",
    image: "https://avatars.githubusercontent.com/u/88695658?v=4",
    description: "Quality Assurance Engineer",
    github: "https://github.com/KashifKhaan",
    linkedin: "https://www.linkedin.com/in/mr-kashif-442146214/",
    twitter: "https://x.com/KaxhifKhan",
    isPastSponsor: true,
  },
    {
    name: "Judar",
    image: "https://pbs.twimg.com/profile_images/1625875289795604480/Vghp-Ym6_400x400.jpg",
    description: "Founder @MLSA",
    github: "https://github.com/trongphuhappy",
    linkedin: "#",
    twitter: "https://x.com/Judar_Clitus",
    isPastSponsor: true,
  },
    {
    name: "Kriti Raj",
    image: "https://avatars.githubusercontent.com/u/62815511?v=4",
    description: "Student at IIIT , India",
    github: "https://github.com/kriti-raj",
    linkedin: "#",
    twitter: "https://x.com/kriti___raj",
    isPastSponsor: true,
  },
    {
    name: "Alex Cerezo",
    image: "https://avatars.githubusercontent.com/u/92682715?v=4",
    description: "Software Engineer at Outlier",
    github: "https://github.com/alexcerezo",
    linkedin: "https://www.linkedin.com/in/alexcerezocontreras/",
    twitter: "https://x.com/alexcerezx",
    isPastSponsor: true,
  },
    {
    name: "Monojit Pal",
    image: "https://avatars.githubusercontent.com/u/144504389?v=4",
    description: "Student at St. Thomas' College",
    github: "https://github.com/Monojit-Pal",
    linkedin: "https://www.linkedin.com/in/pal-monojit/",
    twitter: "https://x.com/Monojit__18",
    isPastSponsor: true,
  },
    {
    name: "Chiluka Akshitha",
    image: "https://avatars.githubusercontent.com/u/120377576?v=4",
    description: "Student at IIT Madras",
    github: "https://github.com/AKSHITHA-CHILUKA",
    linkedin: "https://www.linkedin.com/in/akshitha-chiluka-b19245259",
    twitter: "https://x.com/AkshithaChiluka?t=5ztRGbV2DDB6Wf5tlCyHrw&s=09",
    isPastSponsor: true,
  },
    {
    name: "Irfan", 
    image: "https://avatars.githubusercontent.com/u/138690953?v=4",
    description: "Final Year Student",
    github: "https://github.com/iitzIrFan",
    linkedin: "https://www.linkedin.com/in/irfan-shaikh-8b5b94259/",
    twitter: "https://x.com/iitzIrfan",
    isWeSponsor: true,
  },  
    {
    name: "Renato Maynard", 
    image: "https://avatars.githubusercontent.com/u/79546214?v=4",
    description: "M.Sc. in Operations Research",
    github: "https://www.linkedin.com/in/renatomaynardetche/",
    twitter: "https://x.com/codewithdhruba",
    isWeSponsor: true,
  },  

    {
    name: "Dhrubaraj Pati",
    image: "https://avatars.githubusercontent.com/u/146111647?v=4",
    description: "Student at SVU",
    github: "https://github.com/codewithdhruba01",
    linkedin: "#",
    twitter: "#",
    isWeSponsor: true,
  }, 
  {
    name: "Carlos Romero",
    image: "https://avatars.githubusercontent.com/u/119690391?v=4",
    description: "CS Student of La Salle",
    github: "https://github.com/carlosromerorodriguez",
    linkedin: "https://www.linkedin.com/in/carlos-romero-rdgz/",
    isWeSponsor: true,
  },
  {
    name: "Shivansh Saxena",
    image: "https://avatars.githubusercontent.com/u/112249407?v=4",
    description: "Intern at Geo Softech",
    github: "https://github.com/ShivanshPlays",
    linkedin: "https://www.linkedin.com/in/shivansh-saxena-288785168/",
    isWeSponsor: true,
  },
  {
    name: "Mastan Sayyad",
    image: "https://avatars.githubusercontent.com/u/101971980?v=4",
    description: "Web Deveoper at SWOC",
    github: "https://github.com/MastanSayyad",
    linkedin: "https://www.linkedin.com/in/mastan-sayyad/",
    twitter: "https://x.com/mastansayyad02",    
    isWeSponsor: true,
  },
  {
    name: "GSSOC",
    image: "https://avatars.githubusercontent.com/u/166525102?s=200&v=4",
    description: "Girlscript Organisation",
    github: "https://github.com/GSSoC24",
    linkedin: "https://www.linkedin.com/company/girlscriptsoc/posts/?feedView=all",
    isWeSponsor: true,
  },
  {
    name: "Anshika Tiwari",
    image: "https://avatars.githubusercontent.com/u/143124119?v=4",
    description: "Student, ",
    github: "https://github.com/anshikatiwari20",
    linkedin: "https://www.linkedin.com/in/anshika-tiwari-/",
    twitter: "https://x.com/anshikat_20",
    isWeSponsor: true,
  },
  {
    name: "Meet Jain",
    image: "https://avatars.githubusercontent.com/u/133582566?v=4",
    description: "Student @ IIIT Jabalpur",
    github: "https://github.com/Meetjain1",
    linkedin: "https://www.linkedin.com/in/meet-jain-413015265/",
    twitter: "https://x.com/Meetjain_100",
    isWeSponsor: true,
  },
  {
    name: "Hemant Lohar",
    image: "https://avatars.githubusercontent.com/u/131635107?v=4",
    description: "Student, India",
    github: "https://github.com/Hemantlohar",
    linkedin: "#",
    isWeSponsor: true,
  },
    {
    name: "Chiluka Akshitha",
    image: "https://avatars.githubusercontent.com/u/120377576?v=4",
    description: "Student at IIT Madras",
    github: "https://github.com/AKSHITHA-CHILUKA",
    linkedin: "https://www.linkedin.com/in/akshitha-chiluka-b19245259",
    twitter: "https://x.com/AkshithaChiluka?t=5ztRGbV2DDB6Wf5tlCyHrw&s=09",
    isWeSponsor: true,
  },
  {
    name: "Himangshu Sharma",
    image: "https://avatars.githubusercontent.com/u/120270398?v=4",
    description: "Opensource developer",
    github: "https://github.com/HimangshuSharma01",
    linkedin: "https://www.linkedin.com/in/himangshusharma01",
    isWeSponsor: true,
  },
  {
    name: "Siddheya Kulkarni",
    image: "https://avatars.githubusercontent.com/u/115717746?v=4",
    description: "Student, Opensource developer",
    github: "https://github.com/Asymtode712",
    linkedin: "https://www.linkedin.com/in/siddheya-kulkarni/",
    twitter: "https://x.com/SidKulkarni712",
    isWeSponsor: true,
  },
  {
    name: "Prithwi Hegde",
    image: "https://avatars.githubusercontent.com/u/115262737?v=4",
    description: "Student at JSSSSU",
    github: "https://github.com/Prithwi32",
    linkedin: "https://www.linkedin.com/in/prithwi-hegde/",
    isWeSponsor: true,
  },
  {
    name: "Vansh Chaurasiya",
    image: "https://avatars.githubusercontent.com/u/114163734?v=4",
    description: "Intern at GoComet",
    github: "https://github.com/vansh-codes",
    linkedin: "https://www.linkedin.com/in/vanshchaurasiya24/",
    twitter: "https://x.com/VanshChaurasiy4",
    isWeSponsor: true,
  },
  {
    name: "Hemanth kumar",
    image: "https://avatars.githubusercontent.com/u/106808387?v=4",
    description: "Tech Lead at GSSOC",
    github: "https://github.com/Hemu21",
    linkedin: "https://www.linkedin.com/in/hemu21/",
    twitter: "https://x.com/Hemu21_",
    isWeSponsor: true,
  },
  {
    name: "Eduardo San Martin",
    image: "https://avatars.githubusercontent.com/u/664177?v=4",
    description: "Member of the @vuejs",
    github: "https://github.com/posva",
    twitter: "https://x.com/posva",
    isWeSponsor: true,
  },
  {
    name: "Md Azfar Alam",
    image: "https://avatars.githubusercontent.com/u/100375390?v=4",
    description: "Devops Engineer",
    github: "https://github.com/mdazfar2",
    linkedin: "https://www.linkedin.com/in/md-azfar-alam/",
    twitter: "https://x.com/azfarxx_",
    isWeSponsor: true,
  },
  {
    name: "Ajay Dhangar",
    image: "https://avatars.githubusercontent.com/u/99037494?v=4",
    description: "Founder at CodeHarborHub",
    github: "https://github.com/ajay-dhangar",
    linkedin: "https://www.linkedin.com/in/ajay-dhangar/",
    twitter: "https://x.com/CodesWithAjay",
    isWeSponsor: true,
  },
  {
    name: "Sneha kumari",
    image: "https://avatars.githubusercontent.com/u/95492939?v=4",
    description: "Developer at GHCL",
    github: "https://github.com/Snehsk",
    linkedin: "https://www.linkedin.com/in/sneha-kumari1/",
    isWeSponsor: true,
  },
  {
    name: "Swarnendu Bhandari",
    image: "https://media.licdn.com/dms/image/v2/D5603AQExzsjM2S4ojA/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1724809628013?e=1753920000&v=beta&t=PRD0i8nyd-EVblyVMHkJWJrCrLxcmsB5bJWsPOa46x8",
    description: "Student at IIT Kharagpur",
    github: "https://github.com/Swarnendu0123",
    linkedin: "https://www.linkedin.com/in/swarnendu-bhandari/",
    isWeSponsor: true,
  },
  {
    name: "Alex Cerezo",
    image: "https://avatars.githubusercontent.com/u/92682715?v=4",
    description: "Developer at Outlier",
    github: "https://github.com/alexcerezo",
    linkedin: "https://www.linkedin.com/in/alexcerezocontreras",
    twitter: "https://x.com/alexcerezx",
    isWeSponsor: true,
  },
  {
    name: "Aditya Bhaumik",
    image: "https://avatars.githubusercontent.com/u/92214013?v=4",
    description: "Student at VIT",
    github: "https://github.com/aditya-bhaumik",
    linkedin: "https://www.linkedin.com/in/aditya-bhaumik-62b6b2220/",
    isWeSponsor: true,
  },
  {
    name: "Vivek Vardhan",
    image: "https://avatars.githubusercontent.com/u/91594529?v=4",
    description: "Student at VIT",
    github: "https://github.com/vivekvardhan2810",
    linkedin: "https://www.linkedin.com/in/vivek-vardhan-23682521b/",
    isWeSponsor: true,
  },
  {
    name: "Dinesh Talwadker",
    image: "https://media.licdn.com/dms/image/v2/D4D35AQEPaJ17Vq2zMw/profile-framedphoto-shrink_200_200/B4DZgO2PCnHAAc-/0/1752595755484?e=1753635600&v=beta&t=ltSZKvnsXqQavgb4LISSOevZSIU3uhEi--Nx_FtTSQU",
    description: "Co-Founder at Sanity Esports",
    github: "https://github.com/dinxsh",
    linkedin: "https://www.linkedin.com/in/dineshtalwadker/",
    twitter: "https://x.com/dineshcodes",
    isWeSponsor: true,
  },
  {
    name: "Sanya Dureja",
    image: "https://avatars.githubusercontent.com/u/84080312?v=4",
    description: "SDE at Paypal",
    github: "https://github.com/sanyadureja",
    linkedin: "https://www.linkedin.com/in/sanya-dureja-13960122a/",
    isWeSponsor: true,
  },
  {
    name: "Razvan Stoenescu",
    image: "https://avatars.githubusercontent.com/u/4665641?v=4",
    description: "Team lead of Quasar Framework",
    github: "https://github.com/rstoenescu",
    linkedin: "#",
    isWeSponsor: true,
  },
  {
    name: "Sarah Drasner",
    image: "https://avatars.githubusercontent.com/u/2281088?v=4",
    description: "Director at Google",
    github: "https://github.com/sdras",
    linkedin: "#",
    twitter: "https://x.com/sarah_edo",
    isWeSponsor: true,
  },
  {
    name: "Homebrew",
    image: "https://avatars.githubusercontent.com/u/1503512?s=200&v=4",
    description: "package manager for macOS",
    github: "https://github.com/Homebrew",
    linkedin: "#",
    isWeSponsor: true,
  },
];

export default sponsors;
